project:
  type: website
  output-dir: docs

website:
  favicon: "./images/LepEU transparent.png"
 # announcement: 
 #   icon: info-circle
 #   dismissable: true
 #   content: "**Alert** - Registeration is open for the **LepEU Training Workshop** - 26-29 May 2026 - Lisbon, Portugal see the [**News**](./news.qmd)"
 #   type: success
 #   position: below-navbar
  twitter-card: true
  open-graph: true

 
  navbar:
    title: false
    logo: "./images/LepEU transparent.png"
    left:
      - href: index.qmd
        text: Home
#      - href: members.qmd
#        text: Members
      - href: organisation.qmd
        text: Organisation
      - href: species.qmd
        text: Species
 #     - href: datapolicy.qmd
 #       text: Data Sharing
      - text: Resources
        menu:
          - text: Data Sharing
            href: datapolicy.qmd 
          - text: Database Entry
            href: database.qmd
      - href: funding.qmd
        text: Funding
      - href: pubs.qmd #TODO: make blog post like!
        text: Publications
      - href: news.qmd
        text: News
      - href: contact.qmd
        text: Join Us!
  page-footer:  
    center:
      - text: "Copyright 2026 &copy; LepEU Consortium"
    right:
      - text: "{{< fa brands discord size=Huge >}}"
        aria-label: discord
        href: https://discord.gg/ypMYmkftQm
  google-analytics: "G-Z6QF0999FY"
  site-url: https://lepeu.github.io
  repo-url: https://github.com/LepEU/lepeu.github.io
  

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: false
    bootstrap-icons: true
    page-layout: full

