project:
  type: website
  output-dir: docs

website:
  favicon: "./images/LepEU transparent.png"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "See the Post-meeting statement from the first face-to-face **European Lepidoptera Pop Gen Workshop** - 12-16 May 2025 - Montpellier, France on the [**News**](./news.qmd) page"
    type: success
    position: below-navbar
  twitter-card: true
  open-graph: true

 
  navbar:
    title: false
    logo: "./images/LepEU transparent.png"
    left:
  
#      - href: members.qmd
#        text: Members
      - href: organisation.qmd
        text: Organisation
      - href: species.qmd
        text: Strategy
      - text: Resources
        menu:
          - href: samplingOverview.qmd
            text: Sampling Status
          - href: protocols.qmd
            text: Protocols
          - href: guides.qmd
            text: Field Guides & ID
          - href: datapolicy.qmd
            text: Data Usage
          - href: pubs.qmd #TODO: make blog post like!
            text: Publications
          - href: funding.qmd
            text: Funding
          - href: contact.qmd
            text: Join Us!
      - href: news.qmd
        text: News
     
  page-footer:  
    center:
      - text: "Copyright 2025 &copy; LepEU Consortium"
    right:
      - text: "{{< fa brands discord size=Huge >}}"
        aria-label: discord
        href: https://discord.gg/ypMYmkftQm
  google-analytics: "G-Z6QF0999FY"
  site-url: https://lepeu.github.io
  repo-url: https://github.com/LepEU/lepeu.github.io
  

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: false
    page-layout: full


