project:
  type: website
  output-dir: docs

website:
  favicon: "./images/LepEU transparent.png"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - LepEU has cost action funding! pleace check the [**News**](./news.qmd)"
    type: success
    position: below-navbar
  twitter-card: true
  open-graph: true

 
  navbar:
    title: false
    logo: "./images/LepEU transparent.png"
    left:
      - href: index.qmd
        text: Home
      - href: members.qmd
        text: Members
      - href: organisation.qmd
        text: Organisation
      - href: species.qmd
        text: Species
      - href: datapolicy.qmd
        text: Data Sharing
      - href: pubs.qmd #TODO: make blog post like!
        text: Publications
      - href: news.qmd
        text: News
      - href: contact.qmd
        text: Join Us!
  page-footer:  
    center:
      - text: "Copyright 2025 &copy; LepEU Consortium"
    right:
      - text: "{{< fa brands discord size=Huge >}}"
        aria-label: discord
        href: https://discord.gg/ypMYmkftQm
  

format:
  html:
    theme: 
      dark: slate
      light: cosmo
    css: styles.css
    toc: false
    page-layout: full


